# Generated by Django 5.1.7 on 2025-03-06 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_planner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studytask',
            old_name='completed',
            new_name='is_completed',
        ),
        migrations.RemoveField(
            model_name='studytask',
            name='user',
        ),
        migrations.AlterField(
            model_name='studytask',
            name='description',
            field=models.TextField(null=True, blank=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studytask',
            name='due_date',
            field=models.DateTimeField(null=True, blank=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studytask',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Reward',
        ),
    ]
