# Generated by Django 5.1.7 on 2025-04-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studytask',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
