# Generated by Django 5.1.7 on 2025-04-09 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_planner', '0002_studytask_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studytask',
            name='time_commitment',
            field=models.CharField(default='No time commitment specified.', max_length=255),
        ),
    ]
