# Generated by Django 5.1.7 on 2025-03-06 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_planner', '0002_rename_completed_studytask_is_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studytask',
            name='due_date',
            field=models.DateTimeField(null=True, blank=True),
        ),
    ]
