# Generated by Django 5.1.7 on 2025-03-10 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_planner', '0003_alter_studytask_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studytask',
            old_name='is_completed',
            new_name='generated_by_ai',
        ),
        migrations.AlterField(
            model_name='studytask',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
