# Generated by Django 5.1.7 on 2025-03-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_planner', '0005_remove_studytask_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studytask',
            name='daily_breakdown',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='studytask',
            name='study_tips',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='studytask',
            name='weekly_breakdown',
            field=models.JSONField(default=list),
        ),
    ]
