# Generated by Django 5.1.7 on 2025-03-14 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_planner', '0007_achievement_userstreak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='points_needed',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
