# Generated by Django 5.1.7 on 2025-04-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_planner', '0008_alter_achievement_points_needed'),
    ]

    operations = [
        migrations.AddField(
            model_name='studytask',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
